#!/bin/bash
TEMP=$(mktemp)
SECONDS=5
if [ $# -eq 1 ]; then SECONDS="$1"; shift; fi
timeout "${SECONDS}" bash "$@" >"$TEMP" 2>/dev/null
SUCCESS=$?

if [ "$SUCCESS" -eq 0 ]; then
  RESULT="success"
elif [ "$SUCCESS" -eq 124 ]; then
  RESULT="timeout"
else
  RESULT="failure"
fi

echo "<tr class=\"${RESULT}\">"

echo "<td>$(basename "$1")</td>"
echo "<td>${RESULT}</td>"

echo -n "<td>"
cat "$TEMP"
rm "$TEMP"
echo -n "</td>"

echo "</tr>"
exit $SUCCESS
